version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - sqlite_db:/app/db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  sqlite_db: